# Generated by Django 5.0.3 on 2024-03-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
    ]
